window:
  padding:
    x: 15
    y: 15

font:
  size: 10
  normal:
    family: Fira Code
    style: Regular

  bold:
    family: Fira Code
    style: Bold

  italic:
    family: Fira Code
    style: Italic

  bold_italic:
    family: Fira Code
    style: Bold Italic

# Colorscheme: One Dark
colors:
  primary:
    background: "0x282C34"
    foreground: "0xabb2bf"

  normal:
    black: "0x1e2127"
    red: "0xe06c75"
    green: "0x98c379"
    yellow: "0xe5c07b"
    blue: "0x61afef"
    magenta: "0xc678dd"
    cyan: "0x56b6c2"
    white: "0xabb2bf"

  bright:
    black: "0x5c6370"
    red: "0xe06c75"
    green: "0x98c379"
    yellow: "0xe5c07b"
    blue: "0x61afef"
    magenta: "0xc678dd"
    cyan: "0x56b6c2"
    white: "0xffffff"
