name: default
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - numpy
  - scipy
  - sympy
  - jupyter
  - jupyterlab
  - nodejs # needed by jupyterlab
  - jupytext
  - ipython
  - nb_conda
  - nbdime
  - matplotlib
  - xarray
  - netcdf4
  - cartopy
  - pyproj
  - dask
  - dask-labextension
  - numba
  # Linting and style checking
  - black>=20.8b1
  - rope
  - flake8
  # Fatiando
  - pooch
  - verde
  - harmonica
  - rockhound
  - boule
